baseURL: https://1.writeups.cn/
languageCode: zh-cn
defaultContentLanguage: zh
title: WP存档
theme: fluency
enableRobotsTXT: true
summaryLength: 100 # Configure how long the post summary should be on the homepage.
pygmentsUseClasses: true # enable theme-defined highlight style
pygmentsCodefences: true
hasCJKLanguage: false
enableEmoji: true

ignoreErrors:
  - error-remote-getjson
  - error-missing-instagram-accesstoken

# googleAnalytics: UA-XXXXXXXXX-X
# disqusShortName: hugo

minify:
  disableSVG: true

markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  category: categories
  tag: tags

# permalinks:
#   posts: :section/:slug

params:
  author: Hugo Author
  description: "A fluent Hugo theme for writers and bloggers."
  # copyright: "© 2021 &nbsp;<a href='https://github.com/wayjam/hugo-theme-fluency'>Hugo Theme Fluency</a>"

  # main section will be listed at index page
  mainSections:
    - posts
  
  # set number of post of specify type of content
  pageSize:
    index: 10
    list: 10
    archives: 20

  # extra info below post
  # extraMeta: |
  #   this is a license
  #   <p>another line</p>

  disableSocialShare: true
  disableIndexSummary: true
  disableAnchorHeading: false
  disableBreadcrumb: false

  # comment
  disableComment: true
  disableCommentByType:
    - page
  thirdPartyComment: |
    this is your comment
  
  # refer to https://gohugo.io/content-management/formats/
  mathRender: true

  # customScript: |
  #   <script>console.log('hello world')</script>

menu:
  main:
    - identifier: posts
      name: posts
      url: posts/
      weight: 1
    - identifier: ctf.show
      name: ctf.show
      url: ctf.show/
      weight: 2
    - identifier: tags
      name: tags
      url: tags/
      weight: 3
    - identifier: archives
      name: archives
      url: archives/
      weight: 4
    - identifier: about
      name: about
      url: about/
      weight: 5
  # footer:
    # - identifier: twitter
    #   url: "https://twitter.com/gohugoio"
    #   name: Twitter
    # - identifier: github
    #   url: "https://github.com/gohugoio"
    #   name: Github

# Privacy configurations: https://gohugo.io/about/hugo-and-gdpr/
privacy:
  disqus:
    disable: false
  googleAnalytics:
    anonymizeIP: false
    disable: false
    respectDoNotTrack: false
    useSessionStorage: false
  instagram:
    disable: false
    simple: false
  twitter:
    disable: false
    enableDNT: false
    simple: false
  vimeo:
    disable: false
    enableDNT: false
    simple: false
  youtube:
    disable: false
    privacyEnhanced: false
