baseURL: https://1.writeups.cn/
languageCode: zh-cn
defaultContentLanguage: zh
title: WP存档
theme: fluency
enableRobotsTXT: true
summaryLength: 100 # Configure how long the post summary should be on the homepage.
pygmentsUseClasses: true # enable theme-defined highlight style
pygmentsCodefences: true
hasCJKLanguage: true
enableEmoji: true

ignoreErrors:
  - error-remote-getjson
  - error-missing-instagram-accesstoken

# googleAnalytics: UA-XXXXXXXXX-X
# disqusShortName: hugo

minify:
  disableSVG: true

markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  category: categories
  tag: tags

# permalinks:
#   posts: :section/:slug

params:
  author: G
  description: "g@domain"
  # copyright: "© 2021 &nbsp;<a href='https://github.com/wayjam/hugo-theme-fluency'>Hugo Theme Fluency</a>"

  # main section will be listed at index page
  mainSections:
    - posts
  
  # set number of post of specify type of content
  pageSize:
    index: 20
    list: 20
    archives: 20

  # extra info below post
  # extraMeta: |
  #   this is a license
  #   <p>another line</p>

  disableSocialShare: true
  disableIndexSummary: true
  disableAnchorHeading: false
  disableBreadcrumb: false

  # comment
  disableComment: true
  disableCommentByType:
    - page
  #thirdPartyComment: |
  #  this is your comment
  
  # refer to https://gohugo.io/content-management/formats/
  mathRender: true

  customScript: |
    <script>console.log('Hello CTFer 😀')</script>

menu:
  main:
    - identifier: posts
      name: 帖集
      url: posts/
      weight: 1
    - identifier: bugku
      name: bugku
      url: bugku/
      weight: 2
    - identifier: buuoj
      name: buuoj
      url: buuoj/
      weight: 3
    - identifier: ctf.show
      name: ctf.show
      url: ctf.show/
      weight: 5
    - identifier: ctfhub
      name: ctfhub
      url: ctfhub/
      weight: 4
    - identifier: ichunqiu
      name: ichunqiu
      url: ichunqiu/
      weight: 6
    - identifier: pwnhub
      name: pwnhub
      url: pwnhub/
      weight: 7
    - identifier: qsnctf
      name: qsnctf
      url: qsnctf/
      weight: 8
    - identifier: xctf
      name: xctf
      url: xctf/
      weight: 9
    - identifier: tags
      name: 标签
      url: tags/
      weight: 108
    - identifier: archives
      name: 存档
      url: archives/
      weight: 109
    - identifier: about
      name: 关于
      url: about/
      weight: 110
  footer:
    - identifier: vulnhub.cn
      url: "https://www.vulnhub.cn/"
      name: vulnhub.cn
    # - identifier: github
    #   url: "https://github.com/gohugoio"
    #   name: Github

# Privacy configurations: https://gohugo.io/about/hugo-and-gdpr/
privacy:
  disqus:
    disable: false
  googleAnalytics:
    anonymizeIP: false
    disable: false
    respectDoNotTrack: false
    useSessionStorage: false
  instagram:
    disable: false
    simple: false
  twitter:
    disable: false
    enableDNT: false
    simple: false
  vimeo:
    disable: false
    enableDNT: false
    simple: false
  youtube:
    disable: false
    privacyEnhanced: false
